# Generated by Django 3.1.4 on 2020-12-31 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Genre Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numberInStock', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxLengthValidator(255)])),
                ('dailyRentalRate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxLengthValidator(255)])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
        ),
    ]
